[package]
name = "configurafox"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.37"

pathdiff = "0.2.1"

html_editor = { git = "https://github.com/loovjo/escaping_html_editor", branch = "master" }

katex = "0.4"
syntect = "5.0.0"
